const actionTypes = {ADD_DATA: "ADD_DATA",
    ADD_DATA_LOADING: "ADD_DATA_LOADING",
    ADD_DATA_ERROR: "ADD_DATA_ERROR",
    GET_RECIPES: "GET_RECIPES",
    GET_RECIPES_START_LOADING: "GET_RECIPES_START_LOADING",
    GET_RECIPES_ERROR: "GET_RECIPES_ERROR",
    SAVE_RECIPE: "ADD_RECIPE",
    DELETE_RECIPE: "DELETE_RECIPE",
    CLEAR_DAY: "CLEAR_DAY",
    CLEAR_DATA: "CLEAR_DATA",
    CLEAR_RECIPES: "CLEAR_RECIPES",
    REGISTER: "REGISTER",
    LOGIN: "LOGIN",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGOUT: "LOGOUT"
};

export default actionTypes;